# The log file location
log:
  filename: "DAS.log"

# All the databases used by the system
databases:
  dev: "data/DAS.sqlite"
  stage: ""
  prod: ""
  engine: "peewee.SqliteDatabase"
# For every config option for flask
# For every table in the database, add an item here
models:
  mainDB:
  - Role
  - User
  - UserRole
<<<<<<< HEAD
  - Food
  - Profile
=======
  - Post
  - Notification
  - Request
  - File
>>>>>>> parent of 9e7bcc7... Mering with master
  
flask:
  secret_key: '123456790'
  debug: True
flask_security:
  security_password_hash: "pbkdf2_sha512"
  security_password_salt: "ATGUOHAELKiubahiughaerGOJAEGj"
  
# this makes the navigation bar     #src: "/static/images/NavLogo.png"
<<<<<<< HEAD
mainMenu:
  - title: "Index"
    link: "/"
  - title: "Profile"
    link: "/profile"
=======
LaborNavibar:
  - title: "DAS Database"
    link: "/index"
  - title: "Upload"
    link: "/upload"
  - title: "Requests"
    link: "/requests"
    
StudentNavibar:
  - title: "DAS Database"
    link: "/index"
  - title: "Request Alt. Text"
    link: "/request"
>>>>>>> 9c35178847f7ffcfba3bec48c69e42fc82e14e93

fileOperations:
  allowedExtension:
    pdf: "pdf"
    doc: "doc"
    docx: "docx"
  allowedSize:
    size: 8000000
  dataPaths:
    uploads: "static/files/uploads"
    zips: "static/files/zips"
    temp: "static/files/tmp"